use polars::prelude::*;

pub fn init_dataframe() -> DataFrame {
    // Read country-to-region map and convert to lazyframe
    let lf_countries_continents: LazyFrame = LazyCsvReader::new("./data/countries-continents.csv").finish().unwrap();

    // Read country population data
    let lf_country_pop: LazyFrame = LazyCsvReader::new("./data/Country_Population_Data.csv").finish().unwrap();

    // let lf_gen_region: LazyFrame = LazyCsvReader::new("./data/plastic_waste_generation/total_region.csv").finish().unwrap();
    // Read total generated by country data
    let lf_gen_country: LazyFrame = LazyCsvReader::new("./data/plastic_waste_generation/total_country.csv").finish().unwrap();

    // Read total mismanaged by region data for years 2010 and 2019 only
    let lf_mis_region: LazyFrame = LazyCsvReader::new("./data/mismanaged_waste/total.csv").finish()
                                                                                          .unwrap()
                                                                                          .filter(col("Year").eq(lit(2010))
                                                                                              .or(col("Year").eq(lit(2019))));
    // Read per capita mismanaged by country data
    let lf_mis_country: LazyFrame = LazyCsvReader::new("./data/mismanaged_waste/per_capita.csv").finish().unwrap();

    // Read emit probability by country data
    let lf_prob_country: LazyFrame = LazyCsvReader::new("./data/probability_of_ocean_pollution/total.csv").finish().unwrap();

    // Read per capita emitted by country data
    let lf_emit_capita: LazyFrame = LazyCsvReader::new("./data/plastic_emitted_to_ocean/per_capita.csv").finish().unwrap();
    // let lf_emit_total: LazyFrame = LazyCsvReader::new("./data/plastic_emitted_to_ocean/total.csv").finish().unwrap();
    

    /*
     * Add continent/region column to total generated by country data
     */
    let lf_2010_country: LazyFrame = lf_gen_country
                                     .left_join(lf_countries_continents.clone(),
                                                 col("Entity"),
                                                 col("Country"))
                                    // We probably lost some countries here because of the join
                                      .select(&[col("Entity"),
                                                col("Code"),
                                                col("Continent")]);
    
    /*
     * Add continent/region column to total mismanaged by country data ...
     */
    let lf_2019_country: LazyFrame = lf_mis_country
                                     .left_join(lf_countries_continents,
                                                 col("Entity"),
                                                 col("Country"))
                                     /* ... join on country and year with per capita emitted data ... */
                                     .join_builder()
                                         .with(lf_emit_capita)
                                         .how(JoinType::Inner)
                                         .on(&[col("Entity"),
                                               col("Year")])
                                         .finish()
                                     .select(&[col("Entity"),
                                               col("Code"),
                                               col("Continent"),
                                               col("Mismanaged plastic waste per capita (kg per year)").alias("Mismanaged per capita"),
                                               col("Mismanaged plastic waste to ocean per capita (kg per year)").alias("Emit per capita")])
                                     /* ... join on country with population data ... */
                                     .join_builder()
                                         .with(lf_country_pop)
                                         .how(JoinType::Inner)
                                         .left_on(&[col("Entity")])
                                         .right_on(&[col("Country Name")])
                                         .finish()
                                     /* ... join on country with emit probability data ... */
                                     .inner_join(lf_prob_country,
                                                 col("Entity"),
                                                 col("Entity"))
                                     /* ... select newly calculated total amounts from per capita
                                      * and population data ... */
                                     .select(&[col("Entity"),
                                               col("Code"),
                                               col("Continent"),
                                               col("Mismanaged per capita").alias("2019 Total Mismanaged") * col("2019"),
                                                col("Emit per capita").alias("2019 Total Emitted") * col("2019"),
                                               col("Probability of plastic being emitted to ocean").alias("2019 Prob Emitted")])
                                     /* ... join on continent/region with mismanaged by region data for 2019 ... */
                                     .inner_join(lf_mis_region.clone(),
                                                 col("Continent"),
                                                 col("Entity"))
                                     .filter(col("Year").eq(lit(2019)))
                                     /* ... select with newly calculated percent of region's
                                      * mismanaged by country. */
                                     .select(&[col("Entity"),
                                               col("Code"),
                                               col("Continent"),
                                               col("2019 Total Mismanaged"),
                                               col("2019 Total Mismanaged").alias("2019 % of Region Mismanaged") / col("Mismanaged") / lit(10),
                                               col("2019 Total Emitted"),
                                               col("2019 Prob Emitted")]);

    /* 
     * Merge 2010 country attributes with 2019 attributes ...
     */
    let lf_country: LazyFrame = lf_2010_country
                                .inner_join(lf_2019_country, col("Entity"), col("Entity"))
                                .inner_join(lf_mis_region,
                                            col("Continent"),
                                            col("Entity"))
                                .filter(col("Year").eq(lit(2010)))
                                /* ... calculate and select 2010 total mismanaged data by country ... */
                                .select(&[col("Entity"),
                                          col("Code"),
                                          col("Continent"),
                                          col("2019 % of Region Mismanaged").alias("2010 Total Mismanaged") * col("Mismanaged") * lit(10),
                                          col("2019 Total Mismanaged"),
                                          col("2019 Total Emitted"),
                                          col("2019 Prob Emitted")])
                                /* ... use 2010 total mismanaged to calculate the 2010 total
                                 * emitted by country. */
                                .select(&[col("*"),
                                          col("2010 Total Mismanaged").alias("2010 Total Emitted") / lit(100) * col("2019 Prob Emitted")]);

    // Calculate change per year
    let lf_slope: LazyFrame = lf_country
                                .select(
                                    &[
                                        col("Entity"),
                                        col("Code"),
                                        col("Continent"),
                                        col("2019 Total Emitted"),
                                        col("2010 Total Emitted"),
                                    ]
                                    )
                                .with_column(
                                    (col("2019 Total Emitted").alias("Change Per Year")-col("2010 Total Emitted"))/lit(9)
                                    );

    return lf_slope.collect().unwrap();
}
